# -*- coding: utf-8 -*-
"""Stability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztPdojgGGYsnJI1IbHK2-N_ZKzw3qZDX
"""

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
import sys
import os
import json
import inspect
import numpy as np
import pandas as pd
import scipy.sparse as sp
import matplotlib.pyplot as plt

PROJECT_ROOT = Path("/content/drive/MyDrive/large_scale_graph_final_project/Experiment2").resolve()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT_ROOT =", PROJECT_ROOT)
print("Exists:", PROJECT_ROOT.exists())
print("In sys.path:", str(PROJECT_ROOT) in sys.path)
print("Top files:", sorted([p.name for p in PROJECT_ROOT.iterdir()])[:30])
print("Python files:", sorted([p.name for p in PROJECT_ROOT.glob("*.py")]))

!pip install torch_geometric

import torch
print("torch version:", torch.__version__)
print("cuda available:", torch.cuda.is_available())

import recommendation_config as rcfg
print("import recommendation_config ok")
print(rcfg.__file__)

import inspect
from train_recommendation import (
    TrainConfig,
    Stage1Artifacts,
    ModelSpec,
    load_stage1_artifacts,
    train_one_model,
)

print("Imported train_recommendation successfully.")
print("RecommendationConfig signature:", inspect.signature(rcfg.RecommendationConfig))

import recommendation_config as rcfg
from train_recommendation import (
    TrainConfig,
    Stage1Artifacts,
    ModelSpec,
    load_stage1_artifacts,
    train_one_model,
)

print("Imported successfully.")
print("RecommendationConfig signature:", inspect.signature(rcfg.RecommendationConfig))

config = rcfg.RecommendationConfig()

print("Config created successfully.")
print("root       =", config.root)
print("data_dir   =", config.data_dir)
print("results_dir=", config.results_dir)

print("\nPath checks:")
print("root exists?        ", config.root.exists())
print("data_dir exists?    ", config.data_dir.exists())
print("results_dir exists? ", config.results_dir.exists())

print("\nArtifact names:")
for k, v in config.artifact_names.items():
    print(f"{k:28s} -> {v}")

stage1 = load_stage1_artifacts(config)

print("Loaded Stage1Artifacts.")
print("user_features shape:", stage1.user_features.shape)
print("item_genre_features shape:", stage1.item_genre_features.shape)
print("train_matrix shape:", stage1.train_matrix.shape)
print("source_operator shape:", stage1.source_operator.shape)
print("target_operator shape:", stage1.target_operator.shape)

def edge_dropout_sparse(mat: sp.csr_matrix, dropout_rate: float, rng: np.random.Generator) -> sp.csr_matrix:
    if not (0.0 <= dropout_rate < 1.0):
        raise ValueError(f"dropout_rate must be in [0,1), got {dropout_rate}")

    coo = mat.tocoo(copy=True)
    if coo.nnz == 0:
        return mat.copy().tocsr()

    keep_mask = rng.random(coo.nnz) > dropout_rate
    dropped = sp.csr_matrix(
        (coo.data[keep_mask], (coo.row[keep_mask], coo.col[keep_mask])),
        shape=mat.shape,
        dtype=coo.dtype,
    )
    return dropped.tocsr()


def edge_weight_noise_sparse(mat: sp.csr_matrix, sigma: float, rng: np.random.Generator) -> sp.csr_matrix:
    if sigma < 0:
        raise ValueError(f"sigma must be >= 0, got {sigma}")

    coo = mat.tocoo(copy=True)
    if coo.nnz == 0:
        return mat.copy().tocsr()

    noise = rng.normal(loc=0.0, scale=sigma, size=coo.nnz).astype(np.float32)
    new_data = np.clip(coo.data.astype(np.float32) + noise, a_min=0.0, a_max=None)

    noised = sp.csr_matrix(
        (new_data, (coo.row, coo.col)),
        shape=mat.shape,
        dtype=np.float32,
    )
    return noised.tocsr()


def node_feature_noise_dense(x: np.ndarray, sigma: float, rng: np.random.Generator) -> np.ndarray:
    if sigma < 0:
        raise ValueError(f"sigma must be >= 0, got {sigma}")

    noise = rng.normal(loc=0.0, scale=sigma, size=x.shape).astype(np.float32)
    return (x.astype(np.float32) + noise).astype(np.float32)

def make_perturbed_stage1(
    stage1: Stage1Artifacts,
    perturb_type: str | None,
    strength: float,
    seed: int = 42,
) -> Stage1Artifacts:
    rng = np.random.default_rng(seed)

    user_features = stage1.user_features.copy()
    source_operator = stage1.source_operator.copy().tocsr().astype(np.float32)
    target_operator = stage1.target_operator.copy().tocsr().astype(np.float32)

    if perturb_type is None or perturb_type == "none":
        pass

    elif perturb_type == "edge_dropout":
        source_operator = edge_dropout_sparse(source_operator, strength, rng)
        target_operator = edge_dropout_sparse(target_operator, strength, rng)

    elif perturb_type == "edge_weight_noise":
        source_operator = edge_weight_noise_sparse(source_operator, strength, rng)
        target_operator = edge_weight_noise_sparse(target_operator, strength, rng)

    elif perturb_type == "node_feature_noise":
        user_features = node_feature_noise_dense(user_features, strength, rng)

    else:
        raise ValueError(f"Unknown perturb_type: {perturb_type}")

    return Stage1Artifacts(
        user_features=user_features,
        item_genre_features=stage1.item_genre_features,
        train_matrix=stage1.train_matrix,
        val_matrix=stage1.val_matrix,
        test_matrix=stage1.test_matrix,
        candidate_item_universe=stage1.candidate_item_universe,
        user_masks=stage1.user_masks,
        source_operator=source_operator,
        target_operator=target_operator,
    )

TOP_MODEL_SPECS = [
    ModelSpec(
        run_name="chebnet_fused_a05",
        display_name="ChebNet fused a=0.5",
        model_kind="chebnet",
        graph="fused",
        alpha_mode="fixed",
        alpha_value=0.5,
    ),
    ModelSpec(
        run_name="graphsage_fused_a05",
        display_name="GraphSAGE fused a=0.5",
        model_kind="graphsage",
        graph="fused",
        alpha_mode="fixed",
        alpha_value=0.5,
    ),
    ModelSpec(
        run_name="fixed_fused_gcn_a05",
        display_name="GCN fused a=0.5",
        model_kind="fixed_fused",
        graph="fused",
        alpha_mode="fixed",
        alpha_value=0.5,
    ),
]
TOP_MODEL_SPECS

train_config = TrainConfig(
    hidden_dim=64,
    dropout=0.3,
    learning_rate=1e-3,
    weight_decay=1e-4,
    max_epochs=100,
    patience=20,
    grad_clip_norm=5.0,
    seed=42,
    eval_batch_size_users=1024,
    smoke_eval_user_limit=None,
    smoke_skip_ranking_eval=False,
    use_enriched_features=True,
    top_book_genres=30,
    highrated_sampling=False,
    highrated_threshold=4.0,
)

train_config

baseline_stage1 = make_perturbed_stage1(stage1, perturb_type="none", strength=0.0, seed=42)

baseline_results, baseline_history, baseline_summary = train_one_model(
    model_spec=TOP_MODEL_SPECS[0],
    stage1=baseline_stage1,
    train_config=train_config,
    config=config,
)

baseline_results

PERTURB_GRID = {
    "edge_dropout": [0.05, 0.10, 0.20, 0.30],
    "edge_weight_noise": [0.05, 0.10, 0.20],
    "node_feature_noise": [0.05, 0.10, 0.20],
}

SEEDS = [42, 43, 44]
PERTURB_GRID

all_results = []
all_histories = {}

for model_spec in TOP_MODEL_SPECS:
    for perturb_type, strengths in PERTURB_GRID.items():
        for strength in strengths:
            for seed in SEEDS:
                print("=" * 100)
                print(
                    f"Running model={model_spec.run_name} | "
                    f"perturb={perturb_type} | strength={strength} | seed={seed}"
                )

                local_train_config = TrainConfig(
                    hidden_dim=train_config.hidden_dim,
                    dropout=train_config.dropout,
                    learning_rate=train_config.learning_rate,
                    weight_decay=train_config.weight_decay,
                    max_epochs=train_config.max_epochs,
                    patience=train_config.patience,
                    grad_clip_norm=train_config.grad_clip_norm,
                    seed=seed,
                    eval_batch_size_users=2048,
                    smoke_eval_user_limit=None,
                    smoke_skip_ranking_eval=False,
                    use_enriched_features=train_config.use_enriched_features,
                    top_book_genres=train_config.top_book_genres,
                    highrated_sampling=train_config.highrated_sampling,
                    highrated_threshold=train_config.highrated_threshold,
                )

                stage1_p = make_perturbed_stage1(
                    stage1=stage1,
                    perturb_type=perturb_type,
                    strength=strength,
                    seed=seed,
                )

                results, history, summary = train_one_model(
                    model_spec=model_spec,
                    stage1=stage1_p,
                    train_config=local_train_config,
                    config=config,
                )

                row = dict(results)
                row["run_name"] = model_spec.run_name
                row["display_name"] = model_spec.display_name
                row["model_kind"] = model_spec.model_kind
                row["perturb_type"] = perturb_type
                row["perturb_strength"] = strength
                row["seed"] = seed

                all_results.append(row)
                all_histories[(model_spec.run_name, perturb_type, strength, seed)] = {
                    "history": history,
                    "summary": summary,
                }

results_df = pd.DataFrame(all_results)
results_df.head()

OUT_DIR = PROJECT_ROOT / "results" / "stability"
OUT_DIR.mkdir(parents=True, exist_ok=True)

results_csv = OUT_DIR / "stability_results.csv"
results_df.to_csv(results_csv, index=False)

print("Saved results to:", results_csv)
print("Rows:", len(results_df))

results_df.columns.tolist()

candidate_ndcg_cols = [c for c in results_df.columns if "test_" in c and "NDCG@20" in c]
print("Candidate test NDCG columns:", candidate_ndcg_cols)

if len(candidate_ndcg_cols) == 0:
    raise ValueError("No test NDCG@20 column found. Please inspect results_df.columns.")
elif len(candidate_ndcg_cols) == 1:
    ndcg_col = candidate_ndcg_cols[0]
else:
    ndcg_col = candidate_ndcg_cols[0]

print("Using ndcg column:", ndcg_col)

summary_df = (
    results_df
    .groupby(["display_name", "model_kind", "perturb_type", "perturb_strength"], as_index=False)
    .agg(
        mean_test_ndcg20=(ndcg_col, "mean"),
        std_test_ndcg20=(ndcg_col, "std"),
        n_runs=(ndcg_col, "count"),
    )
    .sort_values(["perturb_type", "display_name", "perturb_strength"])
)

summary_df

for perturb_type in summary_df["perturb_type"].unique():
    plt.figure(figsize=(8, 5))

    sub = summary_df[summary_df["perturb_type"] == perturb_type].copy()

    for model_name in sub["display_name"].unique():
        cur = sub[sub["display_name"] == model_name].sort_values("perturb_strength")

        x = cur["perturb_strength"].to_numpy()
        y = cur["mean_test_ndcg20"].to_numpy()
        yerr = cur["std_test_ndcg20"].fillna(0).to_numpy()

        plt.plot(x, y, marker="o", label= model_name)
        plt.fill_between(x, y - yerr, y + yerr, alpha=0.2)

    plt.xlabel("Perturbation strength")
    plt.ylabel("Test NDCG@20")
    plt.title(f"Stability - {perturb_type}")
    plt.grid(True)
    plt.legend()
    plt.show()

summary_csv = OUT_DIR / "stability_summary.csv"
summary_df.to_csv(summary_csv, index=False)
print("Saved summary to:", summary_csv)

summary_df

target_model = TOP_MODEL_SPECS[0].display_name

plt.figure(figsize=(8, 5))
sub = summary_df[summary_df["display_name"] == target_model].copy()

for perturb_type in sub["perturb_type"].unique():
    cur = sub[sub["perturb_type"] == perturb_type].sort_values("perturb_strength")
    x = cur["perturb_strength"].to_numpy()
    y = cur["mean_test_ndcg20"].to_numpy()
    yerr = cur["std_test_ndcg20"].fillna(0).to_numpy()

    plt.plot(x, y, marker="o", label=perturb_type)
    plt.fill_between(x, y - yerr, y + yerr, alpha=0.2)

plt.xlabel("Perturbation strength")
plt.ylabel("Test NDCG@20")
plt.title(f"Stability - {target_model}")
plt.grid(True)
plt.legend()
plt.show()